# -*- coding: utf-8 -*-
"""Pert 3 - Project .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z5eyYr_uGOATaCT2aK5aG6BbybYEdDiP
"""

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('kc_house_data.csv')

dataset.corrwith(dataset["price"])

dataset.isnull().sum()

X = dataset.iloc[:, 3:].values
y = dataset.iloc[:, 2].values
print(X)

print(y)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Training the Multiple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#print coefisien and interception
print(regressor.coef_)
print(regressor.intercept_)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

regressor.score(X_test,y_pred)