# -*- coding: utf-8 -*-
"""Pert 4 fixed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAgiSLQ9CDnmwv5oraAtD7ZP6L1Fuc-v
"""

# Importing the libraries
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
import statsmodels.api as sm
from sklearn import preprocessing
import matplotlib.pyplot as plt
import matplotlib.mlab
import seaborn as sn

# Importing the dataset
dataset = pd.read_csv('CarPrice_Assignment.csv')
dataset.head(10)

dataset.info()

dataset.corrwith(dataset["price"])

dataset.corr().style.background_gradient().set_precision(2)

dataset.isnull().sum()

X = np.asarray(dataset[['wheelbase', 'carlength', 'carlength', 'carheight',
                           'curbweight', 'enginesize', 'boreratio', 'horsepower']])
y = np.asarray(dataset['price']) # label / target

# normalization of the dataset
X = preprocessing.StandardScaler().fit(X).transform(X)

# Train-and-Test -Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size = 0.3, random_state = 4)


print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Training the Multiple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
model = regressor.fit(X_train, y_train)

y_pred = model.predict(X_test)
print (y_pred)

print(model.coef_)
print(model.intercept_)

score = model.score(X_test,y_test)*100
print('Accuracy of the model is = ', score)

# accuracy for regression
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

harga = model.predict([[100,4,10,5,100,245,123,19]])
print('harga mobil =', harga)